# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Continuous Integration"

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  continuous-integration:
    name: "Continuous Integration"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.0.0"

      - name: "Run GitHub Action when composer.json is not present and path is not specified"
        continue-on-error: true
        uses: "./"

      - name: "Verify that COMPOSER_ROOT_VERSION environment variable has not been set"
        run: |
          if [[ ! -z "${COMPOSER_ROOT_VERSION}" ]]; then
            echo "COMPOSER_ROOT_VERSION environment variable has been unexpectedly set to \"${COMPOSER_ROOT_VERSION}\"."

            exit 1
          fi

          echo "COMPOSER_ROOT_VERSION environment variable has not been set."

      - name: "Run GitHub Action when composer.json is not present"
        continue-on-error: true
        uses: "./"
        with:
          path: ".build/composer-json/present/no"

      - name: "Verify that COMPOSER_ROOT_VERSION environment variable has not been set"
        run: |
          if [[ ! -z "${COMPOSER_ROOT_VERSION}" ]]; then
            echo "COMPOSER_ROOT_VERSION environment variable has been unexpectedly set to \"${COMPOSER_ROOT_VERSION}\"."

            exit 1
          fi

          echo "COMPOSER_ROOT_VERSION environment variable has not been set."

      - name: "Run GitHub Action when composer.json is present but does not have branch-alias defined"
        uses: "./"
        with:
          path: ".build/composer-json/present/yes/branch-alias/defined/no"

      - name: "Verify that COMPOSER_ROOT_VERSION environment variable has not been set"
        run: |
          if [[ ! -z "${COMPOSER_ROOT_VERSION}" ]]; then
            echo "COMPOSER_ROOT_VERSION environment variable has been unexpectedly set to \"${COMPOSER_ROOT_VERSION}\"."

            exit 1
          fi

          echo "COMPOSER_ROOT_VERSION environment variable has not been set."

      - name: "Run GitHub Action when composer.json is present but does not have specified branch-alias defined"
        uses: "./"
        with:
          path: ".build/composer-json/present/yes/branch-alias/defined/yes"
          branch: "foo"

      - name: "Verify that COMPOSER_ROOT_VERSION environment variable has not been set"
        run: |
          if [[ ! -z "${COMPOSER_ROOT_VERSION}" ]]; then
            echo "COMPOSER_ROOT_VERSION environment variable has been unexpectedly set to \"${COMPOSER_ROOT_VERSION}\"."

            exit 1
          fi

          echo "COMPOSER_ROOT_VERSION environment variable has not been set."

      - name: "Run GitHub Action when composer.json is present and has specified branch-alias defined"
        uses: "./"
        with:
          path: ".build/composer-json/present/yes/branch-alias/defined/yes"
          branch: "bar"

      - name: "Verify that COMPOSER_ROOT_VERSION environment variable has been set"
        run: |
          if [[ -z "${COMPOSER_ROOT_VERSION}" ]]; then
            echo "COMPOSER_ROOT_VERSION environment variable has not been set."

            exit 1
          fi

          if [[ "${COMPOSER_ROOT_VERSION}" != "${EXPECTED_COMPOSER_ROOT_VERSION}" ]]; then
            echo "COMPOSER_ROOT_VERSION environment variable has been unexpectedly set to \"${COMPOSER_ROOT_VERSION}\", expected \"${EXPECTED_COMPOSER_ROOT_VERSION}\"."

            exit 1
          fi

          echo "COMPOSER_ROOT_VERSION environment variable has been set to \"${COMPOSER_ROOT_VERSION}\"."
        env:
          EXPECTED_COMPOSER_ROOT_VERSION: "1.0-dev"

      - name: "Run GitHub Action when composer.json is present and has default branch-alias defined"
        uses: "./"
        with:
          path: ".build/composer-json/present/yes/branch-alias/defined/yes"

      - name: "Verify that COMPOSER_ROOT_VERSION environment variable has been set"
        run: |
          if [[ -z "${COMPOSER_ROOT_VERSION}" ]]; then
            echo "COMPOSER_ROOT_VERSION environment variable has not been set."

            exit 1
          fi

          if [[ "${COMPOSER_ROOT_VERSION}" != "${EXPECTED_COMPOSER_ROOT_VERSION}" ]]; then
            echo "COMPOSER_ROOT_VERSION environment variable has been unexpectedly set to \"${COMPOSER_ROOT_VERSION}\", expected \"${EXPECTED_COMPOSER_ROOT_VERSION}\"."

            exit 1
          fi

          echo "COMPOSER_ROOT_VERSION environment variable has been set to \"${COMPOSER_ROOT_VERSION}\"."
        env:
          EXPECTED_COMPOSER_ROOT_VERSION: "2.0-dev"
